# Generated by Django 3.0.2 on 2020-04-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='post',
            field=models.CharField(max_length=1000),
        ),
    ]
