# Generated by Django 3.0.2 on 2020-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200429_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='post',
            field=models.TextField(max_length=1000),
        ),
    ]
